# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'API Call':
    include:
      - '\b\/api-call\b'
      - '\bapi\b'
      - '\bAPI\b'
    exclude: []
  'bug':
    include:
      - '\b\/bug\b'
      - '\bbug[s]?\b'
    exclude: []
  'do not merge':
    include:
      - '\b\/do-not-merge\b'
      - '\bwip\b'
      - '\bWIP\b'
    exclude: []
  'doc required':
    include:
      - '\b\/doc-required\b'
    exclude: []
  'Documentation':
    include:
      - '\b\/documentation\b'
      - '\bdoc[s]?\b'
      - '\bdocumentation\b'
    exclude: []
  'enhancement':
    include:
      - '\b\/enhancement\b'
      - '\bfeat[ure]?\b'
    exclude: []
  'good first issue':
    include:
      - '\b\/good-first-issue\b'
    exclude: []
  'HA':
    include:
      - '\b\/ha\b'
    exclude: []
  'helm':
    include:
      - '\b\/helm\b'
    exclude: []
  'help wanted':
    include:
      - '\b\/help-wanted\b'
      - '\bhelp( me)?\b'
    exclude:
      - '\b\[test(ing)?\]\b'
  'hold':
    include:
      - '\b\/hold\b'
    exclude: []
  'JMESPath':
    include:
      - '\b\/jmespath\b'
    exclude: []
  'LFX':
    include:
      - '\b\/lfx\b'
    exclude: []
  'prometheus':
    include:
      - '\b\/prometheus\b'
    exclude: []
  'question':
    include:
      - '\b\/question\b'
      - '\bquestion\b'
    exclude: []
  'sample policy':
    include:
      - '\b\/sample-policy\b'
      - '\bsample policy\b'
    exclude: []
  'wip':
    include:
      - '\b\/wip\b'
      - '\bwip\b'
      - '\bWIP\b'
    exclude: []  
